### ISSUE TITLE
Custodian removes AND adds "needs review", causing doubled labels 

### ISSUE THREAD

**Issue by Croge32** [newaperio/custodian#16]
![screen shot 2018-01-09 at 3 21 44 pm](https://user-images.githubusercontent.com/1091204/34744449-dcad18fe-f552-11e7-8153-d5f907420597.png)

**Comment by ngscheurich** [comment]
@Croge32, can you describe the sequence of events that leads to this issue?

**Comment by ngscheurich** [comment]
Perfecto. Thanks for the info. 👍
